title: "Sébastien Gomé | Theoretical Fluid Dynamics"
name: "Sébastien Gomé"
description: "Sébastien Gomé (Sebastien Gome or Sebastian Gome) is a theoretical physicist specializing in fluid mechanics and fluid dynamics, with research on turbulence, statistical hydrodynamics and geophysical fluid dynamics."

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  
markdown: kramdown
kramdown:
  math_engine: mathjax

collections:
  posts:
    output: false

locale: en-US


