title: "Sébastien Gomé | Theoretical Fluid Dynamics"
name: "Sébastien Gomé"
description: "sebastien, gome, gomé, physics, mechanics, fluids, turbulence, statistics, geophysics"

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  
markdown: kramdown
kramdown:
  math_engine: mathjax

collections:
  posts:
    output: false

locale: en-US


